import type { Config } from './environment.schemas';

/** Renders the default TypeScript config template for the user project. */
export const renderConfigTemplate = (defaultConfig: Config): string => {
  const registryConfig = defaultConfig.registry
    ? `,
  registry: {
    url: '${defaultConfig.registry.url}',
    token: '${defaultConfig.registry.token ?? ''}',
  }`
    : `,
  // registry: {
  //   url: 'https://npm.pkg.github.com',
  //   token: process.env.PACKAGE_REGISTRY_TOKEN,
  // }`;

  return `import type { Config } from '@suitberks/contract';

// Configuration for contract generation, do not edit this file if you are not sure what you are doing.
// More details about this custom contract library: https://github.com/kalutskii/contract#quick-start

const contractConfig: Config = {
  app: '${defaultConfig.app}',
  contracts: ${JSON.stringify(defaultConfig.contracts)},
  emit: ${JSON.stringify(defaultConfig.emit ?? [])},
  package: {
    name: '${defaultConfig.package.name}',
    version: '${defaultConfig.package.version}',
  }${registryConfig},
};

export default contractConfig;
`;
};

/** Renders a contract manifest template source file for the selected contract. */
export const renderManifestTemplate = (contractName: string): string =>
  `// Define and export all types related to this contract (${contractName}).
// This file will be bundled into ${contractName}.d.ts during "contract build".

// If this contract is listed in config.emit, re-export runtime values only from direct leaf files.
// Keep emitted source files free of unrelated local imports, or they will be pulled into the bundle.

`;
